# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-sub

# Test source C files
APP_C = test-sub.c

# Include unit test module
include $(BUILDROOT)/tests/unittest/os/sys/test-sys.mk
