# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-sub

# Test source C files
APP_C = test-sub.c

# Unit source C files
UNIT_C = sub.c

# Module in which the unit is present
MODULE = os/sys

# Include unittest Makefile
include $(BUILDROOT)/tests/unittest/unittest.mk