# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-add

# Test source C files
APP_C = test-add.c

# Unit source C files
UNIT_C = add.c

# Module in which the unit is present
MODULE = os/sys

# Include unittest Makefile
include $(BUILDROOT)/tests/unittest/unittest.mk