# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-add

# Test source C files
APP_C = test-add.c

# Include unit test module
include $(BUILDROOT)/tests/unittest/os/sys/test-sys.mk