# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-pt

# Test source C files
APP_C += test-pt.c 
APP_C += test-pt-1.c
APP_C += test-pt-2.c

# Include unit test module
include $(BUILDROOT)/tests/unittest/os/sys/test-sys.mk