# Root directory
BUILDROOT = ../../../../..

# Application
APPNAME = test-pt

# Test source C files
APP_C += test-pt.c 
APP_C += test-pt-1.c
APP_C += test-pt-2.c

# Unit source C files
UNIT_C = 

# Module in which the unit is present
MODULE = os/sys

# Include unittest Makefile
include $(BUILDROOT)/tests/unittest/unittest.mk